version: '3'
services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    expose:
      - "8989"
    environment:
      - WORKER_SERVICE_NAME=worker
      - WORKER_SERVICE_PORT=8990
      - WORKER_SERVICE_SCHEME=http
      - WORKER_SERVICE_PATH=internal/api/worker/hash/crack/task
      - MANAGER_SERVICE_PORT=8989
    networks:
      - my-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    expose:
      - "8990"
    environment:
      - MANAGER_SERVICE_NAME=manager
      - MANAGER_SERVICE_PORT=8989
      - MANAGER_SERVICE_SCHEME=http
      - MANAGER_SERVICE_PATH=api/internal/manager/callback
      - WORKER_SERVICE_PORT=8990
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
